apiVersion: "kubaj.kms/v1alpha1"
kind: SecretKMS
metadata:
  name: example-service-account
spec:
  secret: example-service-account
  file: credentials.json
  provider:
    aws:
      data: "AQICAHgrFTRa734vOwBnsBmRYbdFPPIOo6ezR56LpS2c37vfigFsMOA8XlzBJqcBzF5/83xbAAAAbDBqBgkqhkiG9w0BBwagXTBbAgEAMFYGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMC1jclYweIF+iLgQiAgEQgCmLIeNRkIEGgvxOTuL56jgbKZPEQnwlTiykW+9Ohaw/4fisV1Yssm3ToQ=="

---

# Operator will decrypt data in resource above and following resource will be created in Kubernetes
#apiVersion: v1
#kind: Secret
#metadata: 
#  name: example-service-account
#data:
#  credentials.json: dGhlIG1vc3Qgc2VjcmV0IHNlY3JldCBpbiB0aGUgd29ybGQgb2Ygc2VjcmV0cw==