apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: secretkmses.kubaj.kms
spec:
  group: kubaj.kms
  names:
    kind: SecretKMS
    listKind: SecretKMSList
    plural: secretkmses
    singular: secretkms
  scope: Namespaced
  version: v1alpha1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kms-operator
  template:
    metadata:
      labels:
        name: kms-operator
    spec:
      containers:
      - name: kms-operator
        image: kms-operator:latest
        ports:
        - containerPort: 60000
          name: metrics
        args: ["-aws-provider"]
        imagePullPolicy: Always
        env:
        - name: AWS_DEFAULT_REGION
          value: "eu-west-1"          
        - name: AWS_SECRET_ACCESS_KEY
          value: ""
        - name: AWS_SESSION_TOKEN
          value: ""
        - name: AWS_ACCESS_KEY_ID
          value: ""
        - name: WATCH_NAMESPACE
          value: ""
        - name: OPERATOR_NAME
          value: "kms-operator"